# Generated by Django 4.2.2 on 2023-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=60)),
                ("emp_sal", models.IntegerField()),
                ("emp_id", models.IntegerField()),
                ("emp_addr", models.CharField(max_length=100)),
            ],
        ),
    ]
